import streamlit as st

st.image("images/ai_citation_gen.png")

figure_number = st.text_input("Figure Number:", "")

work_title = st.text_input("Title of work/Prompt used:", "")

ai_tool = st.text_input("Title of container (AI tool used):", "")

tool_version_number = st.text_input("AI Version Number:", "")

company = st.text_input("Company who owns the AI:", "")

date_gen = st.text_input("Date generated: (format ex: 20 Apr. 2023)", "")

url = st.text_input("URL of AI tool:", "")

format = st.radio(
    "WWhat type of citation style do you use?",
    ["MLA", "APA", "Chicago"],
)

st.write("### Generated Citation: ")
if format == "MLA":
    st.write(f'Fig. {figure_number}. "{work_title}" prompt, ***{ai_tool}***, version {tool_version_number}, {company}, {date_gen}, {url}.')
elif format == "APA":
    split_date = date_gen.split(" ")
    st.write(f"{company}, ({split_date[-1]}). ***{ai_tool}*** ***{tool_version_number}*** [AI Image Generator], {url}.")
else:
    st.write(f'"{work_title}," image generated by {company}\'s {ai_tool} {tool_version_number}, {date_gen}.')


